TRAIS-Lab/dattri

- .github/workflows/pytest.yml
- dattri/algorithm/influence_function.py
- dattri/func/ihvp.py
- dattri/func/utils.py
- dattri/task.py
- docs/source/api/algorithm.rst
- docs/source/api/task.rst
- docs/source/index.rst
- example/cifar2_resnet9/influence_function_noisy_label.py
- example/mnist_lr/influence_function_noisy_label.py
- test/dattri/algorithm/test_influence_function.py
1. Introduce a new `AttributionTask` class to manage model and checkpoint information, in order to reduce user's workload on extracting internal information of the models needed for some algorithms.
2. Make 2 levels of Attributor API, which makes it easier for users to build customized attributors from our template rather than directly from scratch.
3. Support DataInf as one of the attributors.
4. All examples, unittests and API documents are changed accordingly.
1. Introduce a new `AttributionTask` API, so that users will follow the following template for attributor usage
```python
model = create_model()
def f(params, data_target_pair):
image, label = data_target_pair
loss = nn.CrossEntropyLoss()
yhat = torch.func.functional_call(model, params, image)
return loss(yhat, label.long())
task …
```
> [dattri.algorithm] Add `AttributionTask` abstraction for new API design

- dattri/benchmark/load.py
- dattri/benchmark/models/__init__.py
- dattri/task.py
- docs/source/api/benchmark.rst
- example/mnist_lr/influence_function_lds.py
We need an API help users to download the groundtruth of some benchmark settings as well as the trained model.
The dataset is hosted on https://huggingface.co/datasets/trais-lab/dattri-benchmark/tree/main
```python
from dattri.benchmark.load import load_benchmark
from dattri.task import AttributionTask
from dattri.metrics import lds
model_details, groundtruth = load_benchmark(model="mlp", dataset="mnist", metric="lds")
task = AttributionTask(
model=model_details["model"],
target_func=model_details["target_func"],
checkpoints=model_details["model_full"]
)
attributor = Attributor(task=task)
score = attributor.attribute(
DataLoader(model_details["train_dataset"], shuffle=False),
DataLoader(model_details["test_dataset"], shuffle=False),
)
print("lds:" lds(score, groundtruth))
```
Will add …
> [dattri.benchmark] add benchmark downloading API

- README.md
- dattri/algorithm/base.py
- dattri/algorithm/influence_function.py
- dattri/algorithm/tracin.py
- dattri/algorithm/trak.py
- dattri/task.py
- example/cifar2_resnet9/influence_function_noisy_label.py
- example/mnist_lr/influence_function_lds.py
- example/mnist_lr/influence_function_noisy_label.py
- example/mnist_lr/tracin_noisy_label.py
- example/mnist_lr/trak_noisy_label.py
- test/dattri/algorithm/test_influence_function.py
- test/dattri/algorithm/test_rps.py
- test/dattri/algorithm/test_tracin.py
- test/dattri/algorithm/test_trak.py
We want to make 2 concepts clearer.
- `loss_func`: the loss function used to train the model to be attributed. Normally, this one is used to estimate the changes of parameter when one data point is up/down weighted (IF style) or between each iterations (TracIN style).
- `target_func`: the target function we want to attribute on. This one is normally set to be the same as loss function but not necessarily to be the same. so we make it optional in `dattri.task.AttributionTask`.
1. add `loss_func` in `dattri.task.AttributionTask` and make `target_func` optional.
2. change some internal implementation of `dattri.algorithm` (no API change)
> [dattri.task] Add `loss_func` and make `target_func` optional

- dattri/func/projection.py
- dattri/func/utils.py
- test/dattri/func/test_proj.py
We found that `ChunkedCudaProjector` not working as expected for large models. For Dict input, we found it hard to project without dividing gradients, so we will inherently force dict input to be tensor and split the tensor for projection if it is too large.
- fix chunkcudaprojector bug by forcing tensor input
- add chunkcudaprojector test case for tensor input
Note that I preserve most of the original code and possibly we can come back and make it support dict input (without enforcing it to be tensor).
> [dattri.func] Fix `ChunkedCudaProjector` bug

- docs/source/api/algorithm.rst
- docs/source/api/task.rst
This a quick fix to make `__init__` shown in our document.
> [Doc] Quick fix on the document about `__init__` methods' correct presentation.

- README.md
- dattri/metrics/britteness.py
- experiments/mnist_lr_brittleness.py
This PR is to add brittleness test in metrics. [Reference paper](https://arxiv.org/pdf/2202.00622). This version does not use interpolate.
1. Add brittleness.py under metrics. (After review, we may make it wrapped as a function in metric.py.
2. Add mnist_lr_brittleness.py in experiment folder to show how to use this metric to evaluate Influence Function.
N/A:
> [dattri.metrics] Add brittleness test

- dattri/algorithm/data_shapley.py
- test/dattri/algorithm/test_data_shapley.py
To include the data shapley methods as attribution methods as a completion of the attribution algorithms. Data shapley methods are game-theoretic methods that assign the "relative value of data". This PR focuses on the data shapley values related to KNN.
1. Add new file `dattri.algorithm.data_shapley` and `KNNShalpeyAttributerExact` as the first data shapley value attributer.
2. Add test case for `KNNShalpeyAttributerExact`.
> [dattri.algorithm] Add KNN data shapley

- dattri/algorithm/data_shapley.py
In the previous version of `KNNShalpeyAttributor.attribute`, the test labels are misaligned when there are multiple batches in the test loader. This PR fixes this bug.
> [dattri.algorithm] Fix misalignment in KNN shapley

- dattri/func/utils.py
- dattri/task.py
- test/dattri/test_task.py
1. This PR supports some extensive requirements for calculating the loss/target function and their grad/hessian based on only a portion of the parameter (e.g., some specific layers).
2. The support should be completely wrapped inside the task abstraction.
1. Support the `layer_name` for `task.get_grad_target_func`, `task.get_target_func`, `task.get_grad_loss_func`, and `task.get_loss_func` (previously it will raise a notimplemented error).
TODO: this is the first PR to support partial parameter in dattri. Next PRs will support this feature in high-level attributor APIs.
```python
task = AttributionTask(loss_func=f, model=model, checkpoints=model.state_dict())
grad_func_partial = task.get_grad_loss_func(
layer_name=["fc3.weight", "fc3.bias"],
index=0,  # this is a special additional …
```
> [dattri.task] add partial parameter support for target/loss function and their gradient func

- dattri/func/fisher.py
- dattri/func/projection.py
- dattri/func/utils.py
- dattri/metrics/__init__.py
- dattri/metrics/britteness.py
- dattri/metrics/ground_truth.py
- dattri/metrics/metrics.py
- dattri/task.py
- docs/source/api/benchmark.rst
This PR mainly improves the docstring of files under dattri.func and dattri.metrics.
There are some format inconsistency issues and typos in the docstrings. 
- Improved docstring by making the format more consistent and fixing some typos
- For `dattri/func/utils.py`, changed all `torch.Tensor` to `Tensor` since it is imported
- Fixed a typo in `dattri/task.py`: `_genearte_param_layer_map` -> `_generate_param_layer_map`
- Changed `calculate_loo_groundtruth` in `dattri/metrics/ground_truth.py` to `calculate_loo_ground_truth`. Also changed all the references to this function.
-  N/A: No test will be added. Mainly changed docstring and `torch.Tensor` to `Tensor`. The only code change is a membership function name in `task.py` and a util function in `ground_truth.py`, which should be fine.
> Improve docstring in dattri.func and dattri.metrics

- dattri/metrics/metrics.py
- example/mnist_lr/influence_function_lds.py
- test/dattri/metrics/test_lds.py
Currently, we have all the attributor and `loo_corr` accept score in shape of (num_train_samples, num_test_samples). It would be strange if we have `lds` accept (num_test_samples, num_train_samples). 
1. Change the shape of `score` in `dattri.metrics.metrics.lds` to be (num_train_samples, num_test_samples).
2. Add a cpu transformation since the calculation will happen in cpu for the correlation calculation, this avoid some possible error in users' code if they do not change the device explicitly.
> [dattri.metrics] change the shape of score in `lds` to improve consistency

- dattri/algorithm/base.py
- dattri/algorithm/influence_function.py
- dattri/benchmark/datasets/mnist/mnist_mlp.py
- dattri/func/projection.py
- test/dattri/func/test_proj.py
Re-define the arnoldi projector as 1.0 / sqrt(eigvals) * eigvecs.T * features
- fix the `arnoldi_project`
- add `transform_train_rep` inside arnoldi attributor
- fix a slight typo found in `dattri/benchmark/datasets/mnist/mnist_mlp`
> [dattri.func] Re-implementation of Arnoldi projector

- dattri/algorithm/base.py
- dattri/algorithm/influence_function.py
- dattri/algorithm/tracin.py
- dattri/algorithm/trak.py
- dattri/func/utils.py
- dattri/task.py
- test/dattri/algorithm/test_influence_function.py
- test/dattri/test_task.py
This PR add partial parameters support for IF (except datainf), TracIN, Grad-Dot/Cos, TRAK. The main purpose is to reduce memory usage and make some TDA algorithms be able to scale to larger models.
1. Add partial parameters support for IF, TracIN, Grad-Dot/Cos, TRAK
```python
attributor = Attributor(
task=task,
device=args.device,
layer_name=["fc3.weight", "fc3.bias"],  # the only line changed
)
attributor.cache(train_loader_cache)
with torch.no_grad():
score = attributor.attribute(train_loader, test_loader)
```
3. Revise the partial parameters in `AttributeTask` a little bit.
4. Add some docstring
I also did some experiment on Mnist+MLP setting. Only using `["fc3.weight", "fc3.bias"]`. (TRAK-10 used `["fc2.weight", "fc3.weight", "fc3.bias"]` to avoid singularity). The result of full …
> [dattri.algorithm] add partial parameters support for IF, TracIN, Grad-Dot/Cos, TRAK

- dattri/algorithm/base.py
- dattri/algorithm/influence_function.py
- dattri/algorithm/rps.py
- dattri/algorithm/tracin.py
- dattri/algorithm/trak.py
- dattri/task.py
- test/dattri/test_task.py
We have set most checkpoint index variable as `ckpt_idx` for clarity but the variable names in task.py were still `index`.
This PR renames `index` as `ckpt_idx` in task.py and the places where task is used.
> [dattri.task] Rename index in task to ckpt_idx

- dattri/algorithm/influence_function.py
- dattri/task.py
Currently, IF Attributors (CG, Explicit, Arnoldi) require the second parameter (data) of `loss_func` to be named as "data_target_pair". This PR relax this requirement.
Inspect the loss function's signature and use it in the implementation of IF
> [dattri.algorithm] relax the requirement to the `loss_func`.

- .github/workflows/doc.yml
We will have multiple document checkpoints for each released version as well as the latest version.
Add a new step in `doc.yml` called Deploy-not-main. This will help us to have
1. The latest document (reflect the API of `main` branch) still show on `https://trais-lab.github.io/dattri`
2. The released version document will be shown on `https://trais-lab.github.io/dattri/<branch-name>`
> [Document] support multiple document at the same time.

- README.md
> Minor edits in readme

- .github/workflows/examples_test.yml
- dattri/algorithm/trak.py
- dattri/task.py
- examples/pretrained_benchmark/trak_dropout_lds.py
- examples/readme.md
- experiments/gpt2_wikitext/groundtruth.py
- experiments/gpt2_wikitext/readme.md
- experiments/gpt2_wikitext/score.py
- experiments/gpt2_wikitext/spearman.py
- experiments/gpt2_wikitext/train.py
- Models from huggingface `transformers` is widely used and some additional fix should be included in `dattri`.
- A larger experiment is added (GPT-2 + WikiText-2) to `experiments/`
Experiment added:
- An example GPT-2 + WikiText-2 is added to `experiments/gpt2_wikitext`. Please check https://github.com/TheaperDeng/dattri-public/tree/gpt2_wiki2_hf/experiments/gpt2_wikitext for more detail.
Example added
- An example using Dropout Ensemble in https://github.com/TheaperDeng/dattri-public/blob/gpt2_wiki2_hf/examples/pretrained_benchmark/trak_dropout_lds.py
API change (backlog supported, no need for user code change):
- Add `checkpoints_load_func` to `AttributionTask`, The parameter is used for some model that has special loading strategies, e.g., huggingface model. A typical example for …
> [dattri] Add huggingface example (GPT-2 + WikiText-2) and related bug fix

- .github/workflows/examples_test.yml
- examples/data_cleaning/influence_function_data_cleaning.py
- examples/data_selection/influence_function_data_selection.py
- examples/readme.md
Add an example for data selection.
Add an example for data selection. This script find the top-K low-quality data that "harm" the validation performance the most. The script also evaluate the test performance after removing the top-K low-quality data points.
```bash
Namespace(method='explicit', device='cuda', seed=0, train_size=10000, val_size=10000, test_size=5000, remove_number=100)
Test loss: 0.39373043179512024                                                                                                                                                        
Accuracy: 88.52                                                                                                                                                                       
Test loss (after): 0.38540247082710266 …
```
> [dattri/examples] add data cleaning example

- dattri/algorithm/trak.py
- test/dattri/algorithm/test_trak.py
Added a parameter to trak to allow input of regularization, which is used to help find the inverse matrix.
Previous setting does not allow input regularization.
Adding regularization with defalut value 0.0.
Adding corresponding unit test.
> [dattri.algorithm]  add regularization to trak algorithm

- dattri/algorithm/influence_function.py
Fix improper data loader iteration in IFAttributorDataInf and IFAttributorArnoldi
Previously, both classes repeatedly called next(iter(full_train_dataloader)) inside a loop, which resulted in re-creating the iterator at each iteration and thus always sampling the first batch. This led to redundant and non-representative data being cached or processed.
This patch fixes the issue by instantiating the iterator once before the loop.
> Issue178 solve:  creates only one iterator object instead of creating one every loop

- .github/workflows/doc.yml
- dattri/algorithm/influence_function.py
- dattri/benchmark/datasets/cifar/cifar_resnet9.py
- dattri/benchmark/datasets/imagenet/imagenet_resnet18.py
- dattri/benchmark/load.py
- dattri/func/fisher.py
- dattri/func/utils.py
- dattri/metric/ground_truth.py
- dattri/metric/metrics.py
- dattri/model_util/retrain.py
- dattri/script/dattri_retrain_nanogpt.py
- dattri/task.py
- pyproject.toml
- test/dattri/func/test_proj.py
The updated ruff version introduced some new rules that cause lint errors of the existing codebase. This PR did minimal changes to fix them.
Also fixed missing dependencies needed for tests. This is a bug newly discovered by a change of GitHub Action runners to a blank container (previously the runners had pytorch and tqdm pre-installed). And skipped fast_jl related tests (previously they were skipped by the CUDA availability check but now our runners have access to CUDA).
Also fixed the doc workflow errors due to legacy setup.py install.
Changes for ruff:
- [fix LOG015 errors](https://github.com/TRAIS-Lab/dattri/commit/d6df3fef147924969d88970c8b878940ef9a7b89)
- [fix RUF034 in fisher.py](https://github.com/TRAIS-Lab/dattri/commit/00b5d4b3ff4b3e59473eae82e9d479304d117d3f)
- [fix RUF005 in …
> Fix workflow errors: ruff, test dependencies, and doc
